### ISSUE TITLE
Different Results for Tutorial #2: Iterations and Capacity

### ISSUE THREAD

**Issue by e-lo** [Fast-Trips/fast-trips-tutorial#6]
I have "interesting results" whereas rest of gang did not.

**Comment by e-lo** [comment]
Should be addressed in: https://github.com/Fast-Trips/fast-trips-tutorial/commit/5095c09bef87e3a36d33fedcf6a2059e27eb50f2

**Comment by lmz** [comment]
I updated slide 36 with the looping a little bit -- let me know if it makes sense?  It's confusing...
I also updated the code & tutorial to output every simulation (this was already an optional flag but I added the vehicle output there too for transparency)...  I'm inclined to commit it but also worried about adding too much more since I don't want to break things and it's getting late.

**Comment by lmz** [comment]
I committed updates to fasttrips and the tutorial. Let me know if it messes things up!

**Comment by lmz** [comment]
I didn't update the package yet...

**Comment by e-lo** [comment]
I still get fine results when i run updated notebooks.  Do you get interesting results too?

**Comment by lmz** [comment]
yes 👍
